version: "3"
services:
  django:
    build: .
    container_name: akb-back
    ports:
      - "8000:8000"
    volumes:
      - .:/src
      - static_volume:/static
      - media_volume:/media
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8080"

  nginx:
    image: nginx
    container_name: akb-nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - django

volumes:
  static_volume:
  media_volume: