# Generated by Django 5.1.1 on 2024-10-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='number',
            field=models.CharField(default=1, max_length=144),
            preserve_default=False,
        ),
    ]
